In [1]:
import numpy as np


In [ ]:
a = np.array([4,5,2,4,7,34,7,25,68,3,6,8])
a

array([ 4,  5,  2,  4,  7, 34,  7, 25, 68,  3,  6,  8])

In [ ]:
#llamar a partir de un indice en especifico (aca a partir del 3)
a[3:]

array([ 4,  7, 34,  7, 25, 68,  3,  6,  8])

In [ ]:
#llamamos desde y hasta donde queramos, (aca del 4 al 7)
a[4:7]

array([ 7, 34,  7])

In [ ]:
#llamamos pero con intervalos (aca seria de el 1 y 4 en 4 hasta el final) recordemos que python es desde el 0

a[1::4]

array([ 5, 34,  3])

In [ ]:
#creando arreglos de ceros, en este caso, un array de 5 espacios, todos con 0
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
#dos dimensiones
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
#con unos
np.ones((5,6))


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
#creamos un array, donde le especificamos el limite inferior, y superior, luego numpy colocara datos aleatorios
np.linspace(3, 10, 5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [ ]:
b = np.array([['y','r','y'],['t','r','w']])
print(b)

[['y' 'r' 'y']
 ['t' 'r' 'w']]


In [ ]:
#cuantas dimensiones tiene 
b.ndim

2

In [ ]:
#ordenando
c = np.array([3,4,2,1,7,8,3,5,3,98,342,2])
np.sort(c)

array([  1,   2,   2,   3,   3,   3,   4,   5,   7,   8,  98, 342])

In [ ]:
#ordenando datos

headers = [('nombre','S10'), ('edad', int), ('nacionalidad','S100')]
data = [('Amelie',21,'Francesa'), 
         ('Valerie', 30,'Canadiense'),
         ('Valentina',25,'Inglesa'),
         ('Alejandra',22,'Cubana')]
users = np.array(data,dtype=headers)
np.sort(users, order = 'edad')

array([(b'Amelie', 21, b'Francesa'), (b'Alejandra', 22, b'Cubana'),
       (b'Valentina', 25, b'Inglesa'), (b'Valerie', 30, b'Canadiense')],
      dtype=[('nombre', 'S10'), ('edad', '<i8'), ('nacionalidad', 'S100')])

In [ ]:
#crea un array de numeros hasta 45 en este caso 
np.arange(45)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [ ]:
#con limite inferior y limite superior
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
#de 2 en 2 hasta 60 
np.arange(20,60,2)

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58])

In [ ]:
#una matriz de 3x5 con solo 10 en los valores 
np.full((3,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [ ]:
#creando una matriz diagonal de estos datos
np.diag([0,3,9,10])

array([[ 0,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])